#if UNITY_EDITOR
using System;
using System.Reflection;
using UnityEngine;
using UnityEngine.UI;
using Kamilunavo.PerfectDrop.Gameplay;
using Kamilunavo.PerfectDrop.UI;
namespace Kamilunavo.PerfectDrop.Editor
{
 public static class GalleryMenuValidation
 {
  static int _checks;
  static void Check(bool value,string description){_checks++;if(!value)throw new InvalidOperationException("GALLERY_MENU: "+description);}
  public static void Validate(){_checks=0;Check(!GalleryTheme.IsIvory(Color.clear)&&!GalleryTheme.IsIvory(new Color(.025f,.045f,.08f,.92f)),"old transparent/dark map is rejected by identity contract");string language=PlayerPrefs.GetString("perfectdrop.language","");try{foreach(string lang in new[]{"de","en"}){PlayerPrefs.SetString("perfectdrop.language",lang);foreach(var points in new[]{new Vector2(375,627),new Vector2(430,850),new Vector2(627,355),new Vector2(850,394),new Vector2(190,627)})Fixture(points);}}finally{if(language.Length==0)PlayerPrefs.DeleteKey("perfectdrop.language");else PlayerPrefs.SetString("perfectdrop.language",language);UiMetrics.QaPointScale=null;}Debug.Log("[PerfectDrop] Architectural gallery identity/contrast/reachability PASS "+_checks);}
  static void Fixture(Vector2 points){var root=new GameObject("GalleryMenuProbe");Canvas canvas=null;try{var game=root.AddComponent<StackGame>();Field(game,"<Profile>k__BackingField",new StackProfile{Coins=357,UnlockedLevel=21,TutorialComplete=true});Field(game,"<Run>k__BackingField",new StackRun());Field(game,"<Level>k__BackingField",StackCampaign.Level(1));var hud=root.AddComponent<StackHud>();Field(game,"<Hud>k__BackingField",hud);hud.Build(game);hud.ShowHome();var safe=(RectTransform)typeof(StackHud).GetField("_safe",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(hud);canvas=safe.GetComponentInParent<Canvas>();canvas.GetComponent<CanvasScaler>().enabled=false;canvas.scaleFactor=3;UiMetrics.QaPointScale=3;safe.GetComponent<SafeAreaFitter>().enabled=false;safe.anchorMin=safe.anchorMax=new Vector2(.5f,.5f);safe.sizeDelta=points;typeof(StackHud).GetMethod("LayoutCampaign",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(hud,new object[]{new Rect(0,0,1,1)});Canvas.ForceUpdateCanvases();var map=(RectTransform)safe.Find("LevelMap");Check(GalleryTheme.IsIvory(map.GetComponent<Image>().color),points+" opaque ivory architecture gallery");Check(map.Find("SpecimenGallery/ArchitecturalScene").GetComponent<RawImage>().texture!=null,points+" real owned scene illustration");var tower=map.Find("HeroTower").GetComponent<TowerPreviewGraphic>();Check(tower!=null&&tower.Floors>=5,points+" live mesh hero specimen");Check(tower.rectTransform.rect.height/1>=95,points+" hero larger than old header thumbnail");
   for(int chapter=0;chapter<3;chapter++){var art=map.Find("Chapter"+chapter+"/ChapterArt").GetComponent<RawImage>();Check(art.texture!=null,points+" chapter scene exists "+chapter);if(chapter>0)Check(art.texture!=map.Find("Chapter"+(chapter-1)+"/ChapterArt").GetComponent<RawImage>().texture,points+" distinct chapter scenes");}
   var buttons=map.GetComponentsInChildren<Button>();int primary=0;var safeBounds=UiMetrics.ScreenRect(safe);foreach(var button in buttons){if(button.name.StartsWith("LevelSlot"))continue;var rect=UiMetrics.ScreenRect((RectTransform)button.transform);Check(Inside(safeBounds,rect),points+" fixed target inside safe pane "+button.name);Check(rect.width/3>=47.99f&&rect.height/3>=47.99f,points+" >=48 logical points "+button.name);Contrast(button);if(button.GetComponent<Image>().color==GalleryTheme.Gold)primary++;}Check(primary==1,points+" exactly one gold play/continue action");
   var scroll=map.Find("LevelGalleryScroll").GetComponent<ScrollRect>();Check(scroll.content.childCount==10,points+" all ten chapter levels available");scroll.verticalNormalizedPosition=1;Canvas.ForceUpdateCanvases();Check(Inside(UiMetrics.ScreenRect(scroll.viewport),UiMetrics.ScreenRect((RectTransform)scroll.content.Find("LevelSlot0"))),points+" first level wholly visible");scroll.verticalNormalizedPosition=0;Canvas.ForceUpdateCanvases();Check(Inside(UiMetrics.ScreenRect(scroll.viewport),UiMetrics.ScreenRect((RectTransform)scroll.content.Find("LevelSlot9"))),points+" last level fully reachable");foreach(var button in scroll.content.GetComponentsInChildren<Button>())Contrast(button);
  }finally{if(canvas!=null)UnityEngine.Object.DestroyImmediate(canvas.gameObject);UnityEngine.Object.DestroyImmediate(root);UiMetrics.QaPointScale=null;}}
  static void Contrast(Button button){foreach(var state in new[]{button.colors.normalColor,button.colors.highlightedColor,button.colors.selectedColor,button.colors.pressedColor,button.colors.disabledColor}){var surface=button.GetComponent<Image>().color*state*button.colors.colorMultiplier;foreach(var text in button.GetComponentsInChildren<Text>())Check(GalleryTheme.Contrast(text.color,surface)>=4.5f,"readable "+button.name+" every interactive state");}}
  static bool Inside(Rect outer,Rect inner)=>inner.xMin>=outer.xMin-.5f&&inner.yMin>=outer.yMin-.5f&&inner.xMax<=outer.xMax+.5f&&inner.yMax<=outer.yMax+.5f;
  static void Field(object obj,string name,object value)=>obj.GetType().GetField(name,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(obj,value);
 }
}
#endif
